const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.LOS,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{sharkScale: 0},
	{fishEaten: 0},
	{baseW: 0},
	{baseH: 0},
	{orcaHits: 0},
	{canbeHit: 0},
	{ScrollTo: 0},
	{BoundTo: 0},
	{Shark: 0},
	{Keyboard: 0},
	{Bullet: 0},
	{Wrap: 0},
	{pinkfish: 0},
	{LineOfSight: 0},
	{Orca: 0},
	{Touch: 0},
	{Anchor: 0},
	{ArrowUp: 0},
	{ArrowDown: 0},
	{ArrowLeft: 0},
	{ArrowRight: 0},
	{Mouse: 0},
	{diver: 0},
	{bottle: 0},
	{bag: 0},
	{Rotate: 0},
	{tire: 0},
	{ship: 0},
	{octo: 0},
	{Death: 0},
	{DMG: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	Shark: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	pinkfish: class extends self.ISpriteInstance {},
	Orca: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ArrowUp: class extends self.ISpriteInstance {},
	ArrowDown: class extends self.ISpriteInstance {},
	ArrowLeft: class extends self.ISpriteInstance {},
	ArrowRight: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	diver: class extends self.ISpriteInstance {},
	bottle: class extends self.ISpriteInstance {},
	bag: class extends self.ISpriteInstance {},
	tire: class extends self.ISpriteInstance {},
	ship: class extends self.ISpriteInstance {},
	octo: class extends self.ISpriteInstance {},
	Death: class extends self.ISpriteInstance {},
	DMG: class extends self.ISpriteInstance {}
}